### ISSUE TITLE
Add Cathy Hu to susesecurity team

### ISSUE THREAD

**Issue by danigm** [rpm-software-management/org-admin#1]
Cathy Hu (https://github.com/ca-hu) has just started to work in the SUSE Security Team and it will be nice to be added to the group to give access to review pull requests for the opensuse branch of rpmlint.

**Comment by ca-hu** [comment]
Hi, I would need access to be able to make modifications to the rpmlint opensuse branch, could someone please have a look and check if they can add me to the group? Thanks!

**Comment by mgerstner** [comment]
Ping! Please give Cathy the necessary access to the repository, otherwise we won't be able to properly cover our tasks in our team. Thanks!

**Comment by ffesti** [comment]
Sorry! This fell between the cracks. I guess because we don't really have talked about a process on how to deal with these kind of requests. I invited her to the susesecurity team. Any other permissions she or anyone else needs?

**Comment by pmatilai** [comment]
Uh, so in the meanwhile I added Cathy to the rpmlint-team, because the I saw all these mentions of rpmlint here. Should this be removed or...?

**Comment by ffesti** [comment]
I wonder if someone from Suse should actually be admin for the susesecurity group  @Conan-Kudo

**Comment by mgerstner** [comment]
Thank you, placing her into the `susesecurity` team should suffice. All we need is write access to the rpmlint `opensuse` branch basically, but GitHub doesn't offer more settings more fine-grained than repository level. We have an agreement that we don't touch anything besides our stuff in the `opensuse` branch there.

**Comment by pmatilai** [comment]
Okay looks like this can be closed now.

To clarify, repository owners are generally responsible for managing their groups. The gotcha in the process is that you can't add people to groups unless they also belong to the organization, and for *that*, an organization admin is needed. It's not exactly ideal.
