### ISSUE TITLE
Can we grant the packit-service access for all of our @org repos?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/org-admin#2]
I'm trying to enable Packit in [fedora-distro-aliases](https://github.com/rpm-software-management/fedora-distro-aliases/pull/21), and Packit service doesn't react (while it works just fine in the mock repo).

That said, if the answer to ${summary} is negative, can we please configure it to access the particular repo?

**Comment by praiskup** [comment]
@frostyx fyi

**Comment by praiskup** [comment]
Ping.

**Comment by praiskup** [comment]
Ping.

**Comment by jan-kolarik** [comment]
Apologies for the delay—we overlooked setting up notifications for the `org-admin` group. We're back on track now, and Packit is enabled for all org repositories now :slightly_smiling_face:
